### PR TITLE
Fixing broken url links in README.md and two other .md

### PR DESCRIPTION
**Pull request by niclaz**
I used [this url checking service](https://www.deadlinkchecker.com) on the current build of the github pages and it listed 61 errors

Only some were valid html 4** errors and so I went through the list and made the following edits to improve the data quality.

###Edited listing
- Parallelchain - website url updated
- Brume wallet - website and github urls updated
- Added **sunset** to Zoker wallet - website url is broken and I can not find other information about it searching... [probably a dead](https://twitter.com/etherealHunt/status/1633496991488507906)
- zk money - linked the github repository instead of docs (broken URL) and added **sunset** to its status in table.
- yellow submarine - linked Medium instead of gitbooks docs (broken URL) and added **sunset** to its status in table
- left broken URL for Sacred Finance but added **sunset** to name and status entries in the table. Not a single commit in the github repository since November 2022.
- CIA Protocol - added github link and **sunset** to status, no activity on Github since 2021 or twitter since 2022 and the website is down.
- Coinbook - added github link and **sunset** to status - no activity on Github since April 2022, their twitter and medium have been deleted, and website is down
- COG project - updated website url - formerly cogfi.org now cogcrypto.com
- Boring Protocol - added Github link to project, the url for their website is broken but their project had activity 8 months ago on Github and don't seem to be in sunset state just yet. Nothing this for future revisions of the database.
- Findora CR - from research this was rebranded to [zkDID](https://docs.findora.org/developers/developer-sdks/zkdid-sdk) and there was a v 0.0.1 release in November 2022... **potential sunset project in future**
- Notebook - their docs url was broken, edited to make it work again but this may break again as it does not seem they have it linked anywhere else online. Also searched Github and found not publicly available repository
- kycnot.me - code repository got moved to new gitlab account, updated url
- speakeasy - their website is down, domain has no SSL - I found a repo hosted by xx network and linked that instead as well as some guide I found. Possible sunset project.
- 1RPC - updated docs url and project description and set status to live
- Skiff - updated the url and added team url to database
- Ethermail - added live status and team url to database
- Semaphore - updated one url that needed redirect
- AirGap wallet - updated docs links to tezos sapling guide, added live status, github link, and team url link
- NuCypher - their website is down,  but from activity on github it looks like this might be a false positive of the broken url check (no action taken)
- AnyType - updated their github url
- Highline.dev - I think they rugged... website is broken and all I can find it a Twitter account with 0 tweets on it... adding **sunset** for now
- Decentra Life - their .app website was down, I think the .org url I found is the new one... but probably this might need to be exluded from database (not very privacy focused to be honest)
- BetterCallRaul - Seems that their website is offline, changing their link to a linktree one I found on the twitter account. Potential project sunset.
- anonZK - their [Twitter](https://twitter.com/AnonAZK/with_replies) has not been active since April and the two tools on their subdomains are not reachable... I am adding sunset to the status, to be checked again in future.
- zkchaos - website is down, I added the Github, and after checking Twitter it looks like it might have sunset... pending review
- Namachain - added **sunset** to status and the github link. No activity on Twitter or Github in over a year.
- Sismo - added the **sunset** status as they are fading out the service, code is still available online on Github. Worth to keep listed? [Source](https://twitter.com/dhadrien_/status/1733124453523919332) 
- TeleBridge - found on their Twitter they rebranded in July 2023 to HYPE (https://hype-eth.com) - [source](https://twitter.com/TelebridgeERC/status/1684673716154757120) - have edited their entry to point to HYPE as it also offers web3 privacy tooling
- Automata AnyDao - updated Docs link to a Github repo of the content (404 error)
- Weavemail - rebranded as Weve and had a new url, added live status and team link to the listing
- Beepo App - updated URL and added more information to listing
- XMTP x Lens - added Github link and mainnet status

###Deleted listings
- Duplicate Findora listing under 'Computing Network' section as it was already listed in 'Infrastructure' section and felt that was a more relevant category.
- Bid Shop listing - no other mention online except our repo, seems they rugged themselves.
- stealthpay.cash is a dead project, [creator twitter](https://twitter.com/CryptoADong)
- Void Cash - website, github, and medium have been deleted it seems, twitter account has 0 tweets. [All I could find on Github was this](https://github.com/plotchy/defi-detective/blob/c2bb3cee58223bf52ded40cfd3681e65cbb607d3/00byaddress/000faaf7c3b3c3c63f62edde58b9081525d8bc31.sol#L6)
- Onion mixer - https://onionmixer.gitbook.io/onion-mixer/ is offline and only the information we have on the repo can be found: "Onion Mixer is the first decentralized protocol for anonymous cross-chain transactions." **Dead project in my opinion**
- AnonZK Incognito - incognito.anonzk.io  like the url vcc.anonzk.io the domain is dead and twitter has low activity. Since the above reference to AnonZK is labeled **sunset** I opted to delete this to make the database more lean.
- Arcana Private NFT - links are broken, blog announcement post has been deleted, and only found a Github repo that discusses the idea but I think this feature has been killed.
- Osiris - decenternet.net/osiris - webpage is a 404 and the company seems to have pivoted away from making a web3 browser. Deleted the listing.
- Crypviser Secure Messenger - https://crypviser.network - seems website is broken, went looking and it had issues in May 2022, and then the parent company CVNX seems to have restructured... I think this is a dead product.
[Twitter profile 1](https://twitter.com/CvnxGov/with_replies) + [Twitter profile 2](https://twitter.com/crypviser/with_replies )
- **NOTE: Personal bias in decision** deleted Cirus foundation - https://cirusfoundation.com - as from my reading it seeks to monetize user data and is actually anti-privacy in philosophical positioning. [I leave this link to support my claim](https://support.cirusfoundation.com/en/knowledge/the-5-vs-of-big-data)
- okSign - oksign.app is broken and their Twitter has not been active since Jan 2002, with only a handful of followers, no repository found on Github. Project is deemed dead.
- Literully - searched on Twitter and found that they [dissolved the company in March 2022](https://twitter.com/UnconstrainedM/status/1634855659752804352)

###Added listing

`| [XMTP web3 social](https://xmtp.org/docs/use-cases/deso) | Lens Protocol and CyberConnect apps use XMTP to provide secure, private messaging to their users. | [XMPT Labs Github](https://github.com/xmtp-labs) | mainnet | - |`

Came across this researching XMTP x Lens listing, decided to distinguish the two pages and code repositories

###Other .md files changed
use-case.md
https://nymtech.net/docs/stable/architecture/nym-other-systems > broken link, found an alternative

pagency.md
weird double url in code tried to point to web3 privacy landscape .png > went looking in repo and linked a new image, not 100% sure it is the correct one. Best someone double checks this.

### CODE REVIEW

**Comment by Msiusko** [comment]
What do think about moving "deleted listing" to sunset / pivoted / another name category beyond all categories: 

1. It will help to archive historical perspective.
2. Provide data for researchers.

**Comment by Msiusko** [comment]
One thing we were discussing with @coinmandeer -> is how we "highlight" broken projects in Explorer (visually):
- knowing that they are "scammy", "poor executed", with "broken links"
- also knowing that whole idea behind Explorer is to give a mechanism for comparing different projects (better privacy vs poor privacy, lets say).

It will be great to have that "sunset" disclaimer or similar to notify people before using any project if it has problems. Plus map down "broken" issues to have the abitility to use them within future scoring approach.

**Comment by niclaz** [comment]
> What do think about moving "deleted listing" to sunset / pivoted / another name category beyond all categories:
> 
>     1. It will help to archive historical perspective.
> 
>     2. Provide data for researchers.

Yes good idea

Thinking about it an 'archive.md' or 'graveyard.md' separate from the readme.md file makes more sense than adding it to the end of this file, makes also the main section of the platform 'leaner' in content.

On that new page the code of the sunset projects could be listed by year of they left the active listing on W3P - 2021 / 22 / 23 / etc

When researching I tried to change links to code repositories since websites fail and domains expire after some time. Quite a few times when searching for information on a listed project with the broken url I only found references to it on the W3P readme.md, and all the forked versions hosted on Github, so having it listed somewhere will be useful for future researchers.

**Below is the full code I deleted in this PR - so it can be easily added to any new file:**

`
| [Osiris](https://www.decenternet.net/osiris) | Osiris is the world's first net-neutral browser. | - | - | - | - |

| [okSign](https://www.oksign.app) | Create, Sign and Save eSignatures with smart contracts and permissioned NFTs. | - | - | - | - |

| [Literully](https://literully.com) | a decentralized voting platform that allows users to create and participate in voting on any topic, all without giving up their privacy or control over their data | ([Docs](https://docs.literully.com/articles/))   | - | - | - |

| [Arcana's Private NFT](https://arcana.network/blog/launching-private-nfts-on-arcana/) | new supported format by Arcana preserving privacy within NFT minting | ([Docs](https://docs.beta.arcana.network/docs/conceptpvtnft/))  | - | - | - |

| [Bidshop](https://www.bidshop.io) | The first and only trustless marketplace with encrypted & secret bidding. Opening a new world of gamification and liquidity for NFT's. | - | - | - | - |

| [Onion mixer](https://onionmixer.gitbook.io/onion-mixer/) | Onion Mixer is the first decentralized protocol for anonymous cross-chain transactions. | - | - | - | - |

| [Void cash](https://void.cash) | Decentralized payment protocol. | ([Docs](https://void-cash.gitbook.io/void.cash/)) | - | - | - |

| [StealthPay](https://www.stealthpay.cash) | a stealth address protocol for Ethereum.| ([GitHub](https://github.com/cryptoadong)) | TBD | Ethereum | anon | - | - |

| [Crypviser Secure Messenger](https://crypviser.network/) | The most private messaging app, based on Blockchain technology. | - | - | - | - |

`

Here is also the Cirus foundation entry, I still feel it should be omitted outright. 

`
| [Cirus foundation](https://cirusfoundation.com/your-data/) | With your permission, Cirus makes earning from your data easy! | - | - | - | - |
`

To this we could add the **sunset** projects can be verified for certain to be ending like in the case of Sismo

**Comment by niclaz** [comment]
> One thing we were discussing with @coinmandeer -> is how we "highlight" broken projects in Explorer (visually):
> 
>     * knowing that they are "scammy", "poor executed", with "broken links"
> 
>     * also knowing that whole idea behind Explorer is to give a mechanism for comparing different projects (better privacy vs poor privacy, lets say).
> 
> 
> It will be great to have that "sunset" disclaimer or similar to notify people before using any project if it has problems. Plus map down "broken" issues to have the abitility to use them within future scoring approach.

I see, I don't know... emojis? 

I don't really see how it could be implemented without causing potential harm... let me explain...

I think the platform/Explorer should list sunset projects in the same alpha / not mainnet projects - with a warning to all

The big difference is projects that are not supported any more, or have rugged their online presence (what we call sunset) shouldn't be what a non technical person sees when accessing the information/database, whereas the alpha / not mainnet should be searchable and comparable to other listings... makes sense?

My concern is that without some technical knowledge some users might start using tech/projects which have sunset, and so negatively impacting their privacy. So if they are searchable in the Explorer it should be super clear that a listed project is sunset / no longer maintained / flagged by W3P, beyond it having an effect on the score from the scoring model process.

Just sharing a concern and a possible solution, not something of upmost importance for me.

**Comment by niclaz** [comment]
Created PR 53 to add in a sunset projects archive at bottom of readme.md

https://github.com/web3privacy/web3privacy/pull/53

**Pull request merged**
