### PR TITLE
Updated README with Reclaim Protocol

### PR DESCRIPTION
**Pull request by rohit-goswami**
Updated README file and added Reclaim Protocol under DID and Data Management category. Please merge it.

### CODE REVIEW

**Comment by Msiusko** [comment]
Can't see your commit

**Comment by rohit-goswami** [comment]
https://github.com/web3privacy/web3privacy/pull/72/commits/89749f5010740ecbcdaf8cf1c14d75359c02d1b2

Please check this

**Comment by rohit-goswami** [comment]
Hey @Msiusko, should I raise a new PR if the present one in not valid?

**Comment by Msiusko** [comment]
Make a new PR

**Pull request closed without merging**
